[package]
name = "matrix_server"
version = "0.1.0"
authors = ["Tommy Hudson <thomhuds@protonmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
crossbeam = "0.7.2"
futures-preview = { version = "0.3.0-alpha.18", features = ["compat"] }
percent-encoding = "2"
rand = "0.7.0"
runtime = { git = "https://github.com/rustasync/runtime" }
runtime-tokio = { git = "https://github.com/rustasync/runtime" }
rust-argon2 = "0.5.1"
serde = "1.0"
serde_json = "1.0"
tap = "0.4.0"
tide = { git = "https://github.com/rustasync/tide" }
tokio = "*"
tokio-postgres = { version = "0.4.0-rc.3", features = ["with-uuid-0_7", "with-serde_json-1"] }
toml = "0.5.3"
tracing = "0.1.5"
tracing-fmt = "0.0.1-alpha.3"
tracing-log = "0.0.1-alpha.1"
tracing-futures = { version = "0.0.1-alpha.1", features = ["tokio", "std-future", "futures-01"] }
uuid = { version = "0.7.4", features = ["v4"] }
